name: my-badges

on:
  workflow_dispatch:
  schedule:
    - cron: '17 5 * * 1-5'

permissions:
  contents: write

jobs:
  my-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Update My Badges
        run: npx update-my-badges@1.0.247 ${{ github.repository_owner }} --size=56
        env:
          GITHUB_TOKEN: ${{ secrets.MY_BADGES_TOKEN }}
          GIT_AUTHOR_NAME: ${{ vars.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ vars.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ vars.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ vars.GIT_AUTHOR_EMAIL }}
